### ISSUE TITLE
Some elements disappear on rotation

### ISSUE THREAD

**Issue by gerchicov-bp** [alokc83/MASegmentedControl#1]
I could understand that you don't support the landscape orientation but rotate to the landscape mode and rotate back to the portrait mode - some elements are disappeared. They will appear again if you click on them only

**Comment by alokc83** [comment]
Thanks for reporting. I will look into it.

**Comment by alokc83** [comment]
@gerchicov-bp I tried to reproduce this. But I couldn't. 
Please note that I used the example app for rotation. Which only has 2 or 3 segments. How many segments did you have in when you tried this. 
Little more info would be helpful.

**Comment by alokc83** [comment]
Closing this issue dude to non reproduction
