### ISSUE TITLE
How to change text size in segments?

### ISSUE THREAD

**Issue by yevgeniyzhigadlov** [alokc83/MASegmentedControl#19]
How to change text size in segments?

**Comment by aelarassi** [comment]
@yevgeniyzhigadlov 
Lock in README.md file section [Rounded corner segment:](https://github.com/alokc83/MASegmentedControl#rounded-corner-segment)
Use **UIFont** with font family & size
`        textSegmentedControl.titlesFont = UIFont(name: "OpenSans-Semibold", size: 14)        `

(You can close this issue!)
